---
# tasks file for sshwait

- name: Waiting for SSH to come up
  wait_for:
    host: "{{ item }}"
    port: 22
    delay: 0
    sleep: 5
    timeout: 320
    state: started
  with_items: "{{ server_group }}"
