---
# tasks file for apache

- name: install required packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
  - httpd
  - php
  - php-mysql
  - php-gd

- name: enable httpd service
  service:
    state: started
    enabled: yes
    name: httpd

